# Generated by Django 2.1.5 on 2019-08-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('address', models.TextField(default=None, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('country', models.TextField(default=None, null=True)),
                ('count', models.IntegerField(default=0)),
                ('account', models.TextField(default='AF', null=True)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
