# Generated by Django 2.1.5 on 2019-10-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0011_auto_20191011_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('L', 'Like'), ('C', 'comment')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=None, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commenteduser',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='currentpost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
